### PR TITLE
use wasm library

### PR DESCRIPTION
**Pull request by monlovesmango**
I think this uses the wasm library properly? 

the added files are taken from here: 
https://github.com/Rabbit-Company/Argon2id-WASM/tree/main/dist

disclaimer... I was just doing this for fun as a challenge so I'm sorry if I misunderstood the ask.

### CODE REVIEW

**Review by moonsettler — COMMENTED** [review]
CORS policy in modern browsers won't let this run locally, it needs a webserver.

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///.../argon-bwg/lib/argon2id_worker.js
Module source URI is not allowed in this document: “file:///.../argon-bwg/lib/argon2id_worker.js”
```

**Comment by monlovesmango** [comment]
CORS policy is always so much fun haha. I see what you were asking about now in the chat. I did find this which answers your questions, but you are right that it needs a web server. I realize now that I didn't run into this error bc I was just running from LiveServer from VSCode.

https://stackoverflow.com/questions/48362093/cors-request-blocked-in-locally-opened-html-file

I was following this guide on using wasm files without a bundler and it seems like there are alternative ways to build the wasm file without requiring the use of a script type=module (which is what triggers the CORS it seems like). could probably build the wasm file from the rust file ourselves, but would also need to update the worker file and it would make it hard to validate the dependencies. 

https://tung.github.io/posts/rust-and-webassembly-without-a-bundler/

**Comment by moonsettler** [comment]
if we could get it running with a local webserver on a mint live linux distro like Tails or Ubuntu, i think needing a webserver could be acceptable. the problem is managing binary releases or giving people a huge multi-step setup process would hinder useability.

some people are not even comfortable with exposing seed material to a completely offline live OS boot with no persistence. but i think that's kind of the absolute minimum required precaution.

alternatively we could make it a build from source web app, but again the shell script would need to be able to build it on such an OS without downloading additional dependencies.

**Comment by monlovesmango** [comment]
can you give me a high level build process you envision for someone running this locally? I have minimal experience in general, but even less with minimal dependency apps (which is why I was interested in trying to help out). seems like you wouldn't want to use a bundler which would bring in npm dependencies, are there bundlers without npm? what about docker-izing it with linux distro? happy to try my best to help, and want to make sure I understand what you consider "help" haha.

do you think it is worth pursuing not using a module script and getting rid of the web worker? this would mean that we would be building the wasm file ourselves (as well as the js file that calls the wasm) which would make it harder to verify dependencies but potentially maybe wouldn't need a web server. if not, is it because you are pretty sure CORS will fire anyway or because you want dependencies to be easy to verify?

**Comment by moonsettler** [comment]
ok, so here is how i imagine it could be done other than a local webpage:

the users would download a zip/tar from the github, verify the hash, and unpack it. there would be a shell script that if they execute it builds the web server from source and starts it after it has been built. it would have to do this with what is available on a typical linux distro out of box. i think they all have C compilers.

we have optimized C implementations of Argon2 and i bet plenty of simple static content serving webserver examples. after that is started, the command line window instructs the user to open an url in the browser.

then you can just make an api call to calculate the hash in the local server. (bonus if there is some progress at least the number of iterations completed).

**Comment by moonsettler** [comment]
> do you think it is worth pursuing not using a module script and getting rid of the web worker? this would mean that we would be building the wasm file ourselves (as well as the js file that calls the wasm) which would make it harder to verify dependencies but potentially maybe wouldn't need a web server. if not, is it because you are pretty sure CORS will fire anyway or because you want dependencies to be easy to verify?

yeah, i'm not sure it's worth the effort. i think there is a way to load a wasm locally, but it involves serializing it as a byte array in js source as you can link local javascript files. and i think somehow you can run wasm code from a byte array. i never managed to make it work.

but verifying that mess would be pretty hard.

**Comment by moonsettler** [comment]
webfsd seems like something that could be easily made and installed from source. will test it out later! that gives you a simple static content serving server, and wasm modules should work with that. then it's optional to get rid of wasm and just include some bin functionality.

edit: this is not going to work either, way too many dependencies. would have to install make, open ssl, diet, ...

**Comment by moonsettler** [comment]
so i managed to get this running on an ubuntu live boot out of box with `python3 -m http.server`. that's good enough i guess. however this is bugged as hell! 😂

but it produces the same hash with 1 iteration.

**Comment by moonsettler** [comment]
something like this?
```bash
#!/bin/bash
xdg-open 'http://localhost:8000'

# Ubuntu comes with Python 3.x
if type -t 'python3' > /dev/null; then
python3 -m http.server 8000
exit 0
fi

# Tails OS comes with Python 2.7.16
if type -t 'python' > /dev/null; then
python -m SimpleHTTPServer 8000
exit 0
fi

echo 'Python installation not found!'
exit 1
```

**Comment by monlovesmango** [comment]
wow thats pretty slick. what makes you say "this is bugged as hell!" (haha)?

so this may be a dumb question, but if the seed words are ultimately displayed using javascript what kind of security benefit are we getting from using wasm to do the hashing? is that benefit worth the added complexity of having to start a server, verifying a wasm file, and bringing python into the mix?

**Comment by moonsettler** [comment]
> what makes you say "this is bugged as hell!" (haha)?

it somehow only works with iteration of 1 otherwise the browser just complains about "being slowed down" and the process never seems to stop. i will try to dig into why later, don't worry about it! definitely not production ready tho.

> so this may be a dumb question, but if the seed words are ultimately displayed using javascript what kind of security benefit are we getting from using wasm to do the hashing?

a lot more efficient pow, also we can use near 2GB memory with WASM instead of 1MB with the javascript version (javascript seems to take parabolic time with memory size so there you rather have more cycles, but that's less parallelization resistant than using a lot of memory)

the end goal is to select parameters that are provably taking unreasonable amount of time to crack reasonably strong passphrases, even for an adversary that has access to all the resources on this planet. for this we need to harness the power of PC hardware efficiently.

**Comment by monlovesmango** [comment]
>it somehow only works with iteration of 1 otherwise the browser just complains about "being slowed down" and the process never seems to stop. i will try to dig into why later, don't worry about it! definitely not production ready tho.

ok sounds good. I don't know if this is a clue to the issue, but I tried 
```
python3 -m http.server 8000
```
from command line on my mac and have been able to run 100 iterations without issue
edit: ran 100 iterations from firefox and 1000 iterations from chrome with no issues

thank you for your detailed response! I am thrown by the POW part though, didn't realize that it is (or can be?) part of seed generation. what is being used as the target in this case?

anything else I can do to help?

**Comment by moonsettler** [comment]
the ideal target that it should take about an hour for a reasonably powerful PC.
that would involve 2GB RAM and 4 CPU cores.

but WASM can't really do that, it can only use a single thread and it can't use a full 2GB.
1 thread 1GB is still fairly good. imagine someone having a GPU optimized code, he can run 500 or 1000 threads in parallel, but he only has like 8GB RAM in a GPU on average. that allows us to make estimates on how many years it would take to crack a passphrase if you know (or have a good enough guess at) the entropy source file with all the available hardware.

**Comment by moonsettler** [comment]
> what is being used as the target in this case?

oh sorry, yeah there is no verifiable PoW difficulty target in the sense how bitcoin uses it, but there is mandatory computational difficulty you can't avoid for trying passphrases. maybe PoW is not the right expression. it's more like an extreme form of PBKDF.

**Comment by moonsettler** [comment]
> from command line on my mac and have been able to run 100 iterations without issue
> edit: ran 100 iterations from firefox and 1000 iterations from chrome with no issues

hmm today it also works for me. i have no explanation. yeah the browser nags about getting slowed down but if i ignore it it goes away when it finishes.

i am completely baffled by the benchmark results:
the WASM version ran for 999490ms with the same parameters the js version finished in 266705ms. (apples to oranges as they ran on separate machines but frankly something is wrong here) the antelle WASM+SIMD version calculates the same task under 417ms (that's more in line with what you would expect from WASM)

you can use this to benchmark:
https://antelle.net/argon2-browser/

**Comment by moonsettler** [comment]
benchmarks on the same machine:
this variant:
```
hahs: 5a1ba3e36498bd76d2915717b643a7ec28f58a459a427527c9ccd78d070da2ca
salt: baby don't hurt me!
parallelism:1
memory:1024
iterations: 100
length: 32
Entropy generated: 5bed9d95b6fa8972a842fb229af2dc62bbd3b9929c8a34d0ffe1fd9aa3eb84d7
Generating the mnemonic took 278878ms.
```
antelle version:
```
[00.001] Testing Argon2 using Binaryen native-wasm
[00.001] Calculating hash...
[00.015] Params: pass=5a1ba3e36498bd76d2915717b643a7ec28f58a459a427527c9ccd78d070da2ca, salt=baby don't hurt me!, time=100, mem=1024, hashLen=32, parallelism=1, type=2
[00.559] Encoded: $argon2id$v=19$m=1024,t=100,p=1$YmFieSBkb24ndCBodXJ0IG1lIQ$W+2dlbb6iXKoQvsimvLcYrvTuZKcijTQ/+H9mqPrhNc
[00.559] Hash: 5bed9d95b6fa8972a842fb229af2dc62bbd3b9929c8a34d0ffe1fd9aa3eb84d7
[00.560] Elapsed: 539ms
```

at least the hash is the same.

**Comment by moonsettler** [comment]
mystery solved, this is still using the javascript version.
try deleting the line:
```html
		<script src="lib/Argon2id.min.js"></script>
```

**Comment by monlovesmango** [comment]
wow thats embarrassing. so now it actually uses wasm! good news, it is indeed very fast (even with 1000 iterations). bad news, I got excited and pushed this before realizing that I can't replicate the seed generation from previous commit. have to put this down for now but will look into fixing that.

because deleting that line also removed the Argon2id object, I also had to make some other modifications to replace that object with one that actually uses the wasm.

- the argon2id.js file that is added mostly comes from here, with some methods removed and changed to javascript: https://github.com/Rabbit-Company/Argon2id-WASM/blob/ac9d720d3a387dbc6e556a955d39c1c7ca701db9/src/argon2id.ts

- the argon2id_wasm.js file that is added has no changes.

- the updates to argon2id_worker.js file are that it is no longer a straight copy (which was compiled js) and instead I just put the code from argon2id_worker.ts in there (bc its so short and easier to reason about).



fyi python server seems to be caching files somehow, if you get an error for Argon2id being missing try using another port. (do you happen to know the proper way to stop the caching??)

**Comment by moonsettler** [comment]
> do you happen to know the proper way to stop the caching??

yeah that annoyed me too, i think if you restart the server it should be updated. and the browser also tends to cache.

i think there is a trick where you can just use `"something.js?123"` for versioning and bypassing cache which uses the full source url. only works for references tho.

could also try this i guess:
```python
# NoCacheHTTPServer.py

import http.server

PORT = 8000

class NoCacheHTTPRequestHandler(
    http.server.SimpleHTTPRequestHandler
):
    def send_response_only(self, code, message=None):
        super().send_response_only(code, message)
        self.send_header('Cache-Control', 'no-store, must-revalidate')
        self.send_header('Expires', '0')

if __name__ == '__main__':
    http.server.test(
        HandlerClass=NoCacheHTTPRequestHandler,
        port=PORT
    )
```
then run with
`python NoCacheHTTPServer.py`

**Comment by monlovesmango** [comment]
ok so I literally tested the rabbit company's argon js implementation against their argon wasm implementation by calling their api with all the same variables was getting completely different seeds so I really don't have any confidence in their wasm library (their js library is slow but at least matches antelle's browser demo).

I am abandoning this pr and instead created one that uses antelle's repo. new pr is:
https://github.com/moonsettler/argon-bwg/pull/3

**Pull request closed without merging**
